version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - SERVER=backend
    ports:
      - 8509:8509
    #depends_on:
      #- backend
    volumes:
      - ./frontend:/workspace
    restart: always

  backend:
    build: backend
    environment:
      - IN_DOCKER=True
    ports:
      - 12345:12345
    volumes:
      - ./data:/data
    restart: always
